name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install allure
        
    - name: Run tests
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      run: |
        pytest tests/ --alluredir=allure-results -v
        
    - name: Generate report
      run: |
        allure generate allure-results --clean -o allure-report
        
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report