name: API Tests with Deployment

on:
  push:
    branches: [pramod]
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      actions: write
      checks: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest pytest
        
    - name: Install Java
      run: sudo apt-get install -y default-jre
        
    - name: Install Allure CLI
      run: |
        sudo apt-get install -y wget unzip
        wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.0/allure-commandline-2.24.0.zip
        sudo unzip allure-commandline-2.24.0.zip -d /opt/
        sudo ln -s /opt/allure-2.24.0/bin/allure /usr/bin/allure
        allure --version
        
    - name: Clean previous test artifacts
      run: |
        # Remove all previous test artifacts completely
        rm -rf allure-results/*
        rm -rf allure-report/*
        # Recreate empty directories
        mkdir -p allure-results
        mkdir -p allure-report
        
    - name: Run tests
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      run: |
        # Run tests and ensure results are always generated
        pytest tests/api --alluredir=allure-results -v || true
        
    - name: Generate fresh Allure report
      if: always()
      run: |
        # Clean existing report completely before generation
        rm -rf allure-report/*
        # Generate new report with clean state
        allure generate allure-results --clean -o allure-report
        # Preserve history for trends if it exists
        if [ -d "allure-report/history" ]; then
          cp -r allure-report/history allure-results/
        fi
        
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./allure-report
        force_orphan: true
        keep_files: false