name: Website Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium webdriver-manager pytest-html
    - name: Run tests
      run: |
        pytest --html=report.html --junitxml=report.xml
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html